//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameCompain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int id { get; set; }
        public Nullable<int> FIO { get; set; }
        public Nullable<int> appointment { get; set; }
        public string department { get; set; }
        public string kod { get; set; }
    }
}
