//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameCompain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_visit
    {
        public int id { get; set; }
        public Nullable<int> info { get; set; }
    
        public virtual Info Info1 { get; set; }
    }
}
